Repository sliitsesc/sliitxtreme-web-2024, pull requests merged in 2024-09, with the labels that each got.

#8 Feat/-6-Implement Navigation and Hero section
  src/App.jsx
  src/components/Hero/Hero.jsx
  src/components/Navbar/Navbar.jsx
  src/context/ThemeContext.jsx
  tailwind.config.js
Labels: ready for review

#49 feat/sw45-Added-SEO-optimization
  index.html
  package-lock.json
  package.json
  public/images/og-image/OG_Image.png
  public/robots.txt
  src/components/Info/InfoSection.jsx
  src/main.jsx
  src/routes/home.jsx
Labels: ready for review, changes requested

#50 Feat/awards section
  public/images/OG_Image.png
  public/images/awards/Award 1.png
  public/images/awards/Award 2.png
  public/images/awards/Award 3.png
  src/components/Awards/Awards.jsx
  src/components/Hero/Hero.jsx
  src/components/Info/InfoSection.jsx
  src/components/Stats/Stats.jsx
  src/lib/data/landingPageData.js
  src/routes/home.jsx
  tailwind.config.mjs
Labels: ready for review, changes addressed

#63 Feat/timeline
  src/components/Awards/Awards.jsx
  src/components/Timeline/Timeline.jsx
  src/components/common/Typography/Header.jsx
  src/index.css
  src/lib/data/landingPageData.js
  src/lib/utils/dateTimeUtils.js
  src/lib/utils/timelineUtils.js
  src/routes/home.jsx
  tailwind.config.mjs
Labels: ready for review
